[package]
license = "AGPL-3.0-only"
name = "zinc_cli"
version = "1.0.3"
edition = "2021"

[[bin]]
name = "zn"
path = "src/main.rs"

[dependencies]
zinc_core = { path = "../zinc_core", version = "1.0.3" }
zinc_std = { path = "../zinc_std", version = "1.0.3" }
serde_json = "1.0"
